apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-image-demo
  labels:
    app: python-image-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-image-demo
  template:
    metadata:
      labels:
        app: python-image-demo
    spec:
      containers:
        - name: python-image-demo
          image: ghcr.io/iftikharqureshi/k3s-python-image-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080